### ISSUE TITLE
FromFedora mapping error: key not found: "corporate"

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1313]
```
Error: key not found: "corporate" (1 errors)
```
Examples: druid:mc276xs6185

**Comment by arcadiafalcone** [comment]
This should be a fail error.

**Comment by justinlittman** [comment]
```
2.7.0 :001 > druid = 'druid:mc276xs6185'
2.7.0 :002 > item = Dor.find(druid)
2.7.0 :003 > desc_props = Cocina::FromFedora::Descriptive.props(mods: item.descMetadata
Traceback (most recent call last):
       15: from (irb):3
       14: from app/services/cocina/from_fedora/descriptive.rb:26:in `props'
       13: from app/services/cocina/from_fedora/descriptive.rb:35:in `props'
       12: from app/services/cocina/from_fedora/descriptive.rb:43:in `add_descriptive_elements'
       11: from app/services/cocina/from_fedora/descriptive.rb:43:in `each'
       10: from app/services/cocina/from_fedora/descriptive.rb:44:in `block in add_descriptive_elements'
        9: from app/services/cocina/from_fedora/descriptive/subject.rb:20:in `build'
        8: from app/services/cocina/from_fedora/descriptive/subject.rb:28:in `build'
        7: from app/services/cocina/from_fedora/descriptive/subject.rb:28:in `map'
        6: from app/services/cocina/from_fedora/descriptive/subject.rb:34:in `block in build'
        5: from app/services/cocina/from_fedora/descriptive/subject.rb:69:in `structured_value'
        4: from app/services/cocina/from_fedora/descriptive/subject.rb:69:in `map'
        3: from app/services/cocina/from_fedora/descriptive/subject.rb:69:in `block in structured_value'
        2: from app/services/cocina/from_fedora/descriptive/subject.rb:119:in `simple_item'
        1: from app/services/cocina/from_fedora/descriptive/subject.rb:119:in `fetch'
KeyError (key not found: "corporate")
```

**Comment by justinlittman** [comment]
```
  <subject authority="lcsh">
    <corporate authority="naf" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/no89003525">Mooseheart (School)</corporate>
    <genre authority="lcsh" authorityURI="http://id.loc.gov/authorities/subjects" valueURI="http://id.loc.gov/authorities/subjects/sh99001806">Songs and music</genre>
  </subject>
```
