### ISSUE TITLE
unknown keyword: :object_type when updating collection

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2651]
For druid:bn716nz4568:

```
Error: unknown keyword: :object_type

Backtrace:
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/to_fedora/identity.rb:9:in `apply'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/object_updater.rb:92:in `update_collection'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/object_updater.rb:40:in `run'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/object_updater.rb:16:in `run'
bin/validate-cocina-roundtrip:99:in `validate_druid'
bin/validate-cocina-roundtrip:163:in `block in <main>'
```

**Comment by jcoyne** [comment]
@justinlittman I fixed something like that last week: https://github.com/sul-dlss/dor-services-app/commit/7bbf02ebf62f9fdd85a65361cf435d12904b74a1#diff-ec7abd61bcc6b489e3c566d2106933a434bc5b7af7072a99e9a9bd5062c80615L63

**Comment by jcoyne** [comment]
Looks like the problem is here: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/object_updater.rb#L92
