### ISSUE TITLE
Running bin/validate-to-desc-cocina fails

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2745]
```
Traceback (most recent call last):
| Time: 00:00:00
8: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:215:in `block (4 levels) in in_threads'
7: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:392:in `block (2 levels) in work_in_processes'
6: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:392:in `loop'
5: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:404:in `block (3 levels) in work_in_processes'
4: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:518:in `with_instrumentation'
3: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:405:in `block (4 levels) in work_in_processes'
2: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:76:in `work'
1: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.5/lib/active_support/core_ext/marshal.rb:6:in `load'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.5/lib/active_support/core_ext/marshal.rb:6:in `load': end of file reached (EOFError)
7: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:215:in `block (4 levels) in in_threads'
6: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:392:in `block (2 levels) in work_in_processes'
5: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:392:in `loop'
4: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:404:in `block (3 levels) in work_in_processes'
3: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:518:in `with_instrumentation'
2: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:405:in `block (4 levels) in work_in_processes'
1: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:75:in `work'   /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:78:in `rescue in work': Parallel::DeadWorker (Parallel::DeadWorker)   
```

**Comment by justinlittman** [comment]
Hmmm ... where are your running it?

**Comment by arcadiafalcone** [comment]
On sdr-deploy, from arcadia/dor-services-app.

**Comment by justinlittman** [comment]
Can you try again? I can't replicate.

**Comment by arcadiafalcone** [comment]
Still getting an error:
```
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `fork': unexpected return
Traceback (most recent call last):
| Time: 00:00:01
8: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:215:in `block (4 levels) in in_threads'
7: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:392:in `block (2 levels) in work_in_processes'
6: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:392:in `loop'
5: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:404:in `block (3 levels) in work_in_processes'
4: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:518:in `with_instrumentation'
3: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:405:in `block (4 levels) in work_in_processes'
2: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:76:in `work'
1: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.5/lib/active_support/core_ext/marshal.rb:6:in `load'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.5/lib/active_support/core_ext/marshal.rb:6:in `load': end of file reached (EOFError)
7: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:215:in `block (4 levels) in in_threads'
6: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:392:in `block (2 levels) in work_in_processes'
5: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:392:in `loop'
4: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:404:in `block (3 levels) in work_in_processes'
3: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:518:in `with_instrumentation'
2: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:405:in `block (4 levels) in work_in_processes'
1: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:75:in `work'   /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:78:in `rescue in work': Parallel::DeadWorker (Parallel::DeadWorker)  
```

**Comment by justinlittman** [comment]
I can replicate when actually running the correct exe.

**Comment by jmartin-sul** [comment]
> I can replicate when actually running the correct exe.

`bin/validate-to-desc-cocina` as listed in the title, or a different executable?

also, from your (@justinlittman's) dir, or only from arcadia's?

**Comment by jmartin-sul** [comment]
initial investigation:  seems like an issue with a particular druid.  `bin/validate-to-desc-cocina -s 100` does not trigger the error, but `bin/validate-to-desc-cocina -s 1000` does.
