### ISSUE TITLE
Nil error in mods_normalizer

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dor-services-app#3461]
When running `validate-cocina-roundtrip`:

```
Traceback (most recent call last):================================================================                                                                                    | Time: 00:49:34
        16: from bin/validate-cocina-roundtrip:290:in `<main>'
        15: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:289:in `map'
        14: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:386:in `work_in_processes'
        13: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `create_workers'
        12: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each_with_index'
        11: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each'
        10: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:447:in `block in create_workers'
         9: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'
         8: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'
         7: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:465:in `block in worker'
         6: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:485:in `process_incoming_jobs'
         5: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'
         4: from bin/validate-cocina-roundtrip:291:in `block in <main>'
         3: from bin/validate-cocina-roundtrip:201:in `validate_druid'
         2: from /opt/app/deploy/amcollie/dor-services-app/app/services/cocina/normalizers/mods_normalizer.rb:31:in `normalize_identifier_type'
         1: from /opt/app/deploy/amcollie/dor-services-app/app/services/cocina/normalizers/mods_normalizer.rb:79:in `normalize_identifier_type'
/opt/app/deploy/amcollie/dor-services-app/app/services/cocina/normalizers/mods_normalizer.rb:285:in `normalize_identifier_type_attr': undefined method `xpath' for nil:NilClass (NoMethodError)
```

**Comment by justinlittman** [comment]
@aaron-collier What was the exact command were you running?

**Comment by aaron-collier** [comment]
@justinlittman the normal `bin/cocina-validate-roundtrips -s 100000` ... same exact command I've been running for each of the normalizer tickets...

**Comment by justinlittman** [comment]
The offending object is druid:xv582wk4533.

**Comment by mjgiarlo** [comment]
@justinlittman @aaron-collier I manually reindexed this druid and it looks sparse: https://argo.stanford.edu/view/druid:xv582wk4533

Is this a legit object? It has no descMetadata which is why it's tripping up the MODS normalizer. It appears to be a stub Hydrus object with some default datastream values. @andrewjbtw @amyehodge ideas?

**Comment by andrewjbtw** [comment]
It looks like a Hydrus draft that never finished being made. It also doesn't have the Hydrus datastreams that I'd expect to see, and no workflows either.

**Comment by mjgiarlo** [comment]
I'm not clear on what's the right way to handle cases like these. They can range from:

1. Run the roundtrip again with a different set of druids
2. Remediate the data. No idea how much work this is, or whether it's worth doing for an object of this sort.
3. Make the normalizers more lenient so they don't blow up on data like this.

@justinlittman @andrewjbtw Happy to defer to y'all on the above. My take in the meantime is that this issue needn't be blocking since only a small number of objects are missing titles, *i.e.*, we're not likely to hit them frequently?

**Comment by andrewjbtw** [comment]
This item likely can be purged but it might be good to know if the depositor actually wanted to make a deposit. It's one of those student thesis collections where I think depositing is optional. They may have started and then decided not to deposit in the end.

**Comment by justinlittman** [comment]
@mjgiarlo Regardless of whether this is purged, normalizers should not combust. (Even if purged, it is likely to remain in various druid lists and will cause problems.)

**Comment by mjgiarlo** [comment]
I started working on this, got as far as [this PR](https://github.com/sul-dlss/dor-services-app/pull/3515) which is running into errors on sdr-deploy [1], and decided I couldn't do this work justice while also trying to get virtual objects done. Feel free to use what's in that PR or not. Delete/close if not, please.

1. 
```
$ bin/validate-cocina-roundtrip -f -s 100000
...
Traceback (most recent call last):                                                                                                   
        37: from bin/validate-cocina-roundtrip:290:in `<main>'                                                                       
        36: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:289:in `map'               
        35: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:386:in `work_in_processes' 
        34: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `create_workers'    
        33: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each_with_index'   
        32: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each'              
        31: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:447:in `block in create_wor
kers'                                                                                                                                
        30: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'            
        29: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'              
        28: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:465:in `block in worker'   
        27: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:485:in `process_incoming_jo
bs'                                                                                                                                  
        26: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'   
        25: from bin/validate-cocina-roundtrip:291:in `block in <main>'                                                              
        24: from bin/validate-cocina-roundtrip:225:in `validate_druid'                                                               
        23: from /opt/app/deploy/mjgiarlo/dor-services-app/app/services/cocina/object_creator.rb:13:in `trial_create'                
        22: from /opt/app/deploy/mjgiarlo/dor-services-app/app/services/cocina/object_creator.rb:28:in `create'                      
        21: from /opt/app/deploy/mjgiarlo/dor-services-app/app/services/cocina/object_creator.rb:65:in `create_from_model'           
        20: from /opt/app/deploy/mjgiarlo/dor-services-app/app/services/cocina/object_creator.rb:111:in `create_dro'                 
        19: from /opt/app/deploy/mjgiarlo/dor-services-app/app/services/cocina/object_creator.rb:111:in `tap'                        
        18: from /opt/app/deploy/mjgiarlo/dor-services-app/app/services/cocina/object_creator.rb:112:in `block in create_dro'        
        17: from /opt/app/deploy/mjgiarlo/dor-services-app/app/services/cocina/object_creator.rb:174:in `add_description'            
        16: from /opt/app/deploy/mjgiarlo/dor-services-app/app/services/cocina/to_fedora/identity.rb:16:in `apply_label'             
        15: from /opt/app/deploy/mjgiarlo/dor-services-app/app/services/cocina/to_fedora/identity.rb:42:in `apply_label'             
        14: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/dor-services-9.6.2/lib/dor/models/abstract.rb:79:in `object
Label='                                                                                                                              
        13: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/document.rb:116:in `method_missing'    
        12: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/dynamic_node.rb:70:in `val='           
        11: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/dynamic_node.rb:70:in `each_with_index'
        10: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/dynamic_node.rb:70:in `each'           
         9: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/dynamic_node.rb:78:in `block in val='  
         8: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/term_value_operators.rb:135:in `term_va
lues_append'                                                                                                                         
         7: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/term_value_operators.rb:162:in `insert_
from_template'                                                                                                                       
         6: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/builder.rb:29
5:in `with'                                                                                                                          
         5: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/builder.rb:29
5:in `new'                                                                                                                           
         4: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/builder.rb:33
1:in `initialize'                                                                                                                    
         3: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/term_value_operators.rb:163:in `block i
n insert_from_template'                                                                                                              
         2: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/term_value_operators.rb:163:in `each'  
         1: from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/term_value_operators.rb:169:in `block (
2 levels) in insert_from_template'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/om-3.2.0/lib/om/xml/term_value_operators.rb:169:in `eval': (eval):1: untermi
nated string meets end of file (SyntaxError)
...s e caminhos do ferro, etc.\\' )
...                               ^
```
