### ISSUE TITLE
Type field not found

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4867]
Triggered when running `item_registration_csv_spec.rb` in Argo:
```
dor-services-app-1  | [3627e532-3024-42f8-85b4-02865aae1e58] Cocina::Models::ValidationError (Type field not found):
dor-services-app-1  | [3627e532-3024-42f8-85b4-02865aae1e58]
dor-services-app-1  | [3627e532-3024-42f8-85b4-02865aae1e58] app/models/repository_object_version.rb:51:in `to_cocina'
dor-services-app-1  | [3627e532-3024-42f8-85b4-02865aae1e58] app/models/repository_object_version.rb:47:in `to_cocina_with_metadata'
dor-services-app-1  | [3627e532-3024-42f8-85b4-02865aae1e58] app/services/cocina_object_store.rb:94:in `find'
dor-services-app-1  | [3627e532-3024-42f8-85b4-02865aae1e58] app/services/cocina_object_store.rb:33:in `find'
dor-services-app-1  | [3627e532-3024-42f8-85b4-02865aae1e58] app/controllers/application_controller.rb:64:in `load_cocina_object'
```

**Comment by justinlittman** [comment]
closed by https://github.com/sul-dlss/dor-services-app/pull/4868
