### ISSUE TITLE
Indexing is not keeping up with accessioning

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#5231]
The indexing statuses in Argo have been falling behind lately and I'm guessing the problem is the indexer itself is falling behind or failing to index as items complete accessioning.

As I write this issue, the Argo workflow grid shows 11 items waiting at the start of the accessionWF, but most of these items have actually been accessioned, some almost a day ago. The same problem applies to the 6 items listed as "started" at end-accession.
<img width="1297" alt="Screenshot 2024-11-19 at 5 23 10 PM" src="https://github.com/user-attachments/assets/2d8db35b-734b-4d67-a3d5-e3b62c1af1fc">

The show page has the same problem, where the status line shows "In accessioning" but the workflow display shows all the steps are complete
<img width="945" alt="Screenshot 2024-11-19 at 5 25 13 PM" src="https://github.com/user-attachments/assets/0f371df0-a719-4fa8-9886-2d8b5f4107e3">

Manually reindexing corrects the issue so it seems like the indexing status is getting dropped somewhere while accessioning runs. Without manual reindex, these items will have incorrect statuses until the rolling indexer comes along.

**Comment by jcoyne** [comment]
@justinlittman log should be in `/var/log/apache/error_log`

**Comment by justinlittman** [comment]
@andrewjbtw Are you able to replicate this in any environment or is it sporadic?

**Comment by andrewjbtw** [comment]
I've tried to reproduce this on stage but haven't been able to do it. I can almost certainly make it happen on prod if I can come up with a set of items to update for real.

**Comment by andrewjbtw** [comment]
Most often, I see this issue in ones and twos every few days. For example, there's [an item that was accessioned yesterday](https://argo.stanford.edu/view/druid:rq089xm3950) that is still indexed as "in accessioning."

**Comment by justinlittman** [comment]
This seems to indicate that https://github.com/sul-dlss/argo/issues/3817 has not been resolved.

**Comment by andrewjbtw** [comment]
Possibly, but it was more or less resolved for a while. That earlier issue was when dor-indexing-app was a separate thing.

**Comment by mjgiarlo** [comment]
@justinlittman I see you've been doing some work related to this issue. OK if I assign you and move to in progress? (This issue is showing up on the prod board as needing to be triaged.)

**Comment by justinlittman** [comment]
Logging is shows that there are indexing requests after the indexing request that created the document that is in Solr.

I have 2 remaining theories:
* Multiple indexing requests for the same item are being processed concurrently. For some reason, one of those requests is taking longer, making it the last committed.
* Solr is dropping the commits.

Logging I just put in will allow ruling out the concurrency theory.

**Comment by justinlittman** [comment]
Easier for me to take a look.

**Comment by andrewjbtw** [comment]
@justinlittman for a recent example, I just saw that a large number of items went through releaseWF and are still listed as "waiting" for `update-marc` when it looks like all the releaseWF workflow steps were completed: https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=releaseWF%3Aupdate-marc%3Awaiting

**Comment by justinlittman** [comment]
@andrewjbtw These look good now or am I missing something?

**Comment by andrewjbtw** [comment]
In this case, since it's the releaseWF, the issue isn't the Accessioned status since they are Accessioned before being released. 

The issue is the workflow statuses. All the releaseWF steps are completed according to the workflow server

> <img width="330" alt="Image" src="https://github.com/user-attachments/assets/ca792d81-4647-4e91-8043-e272ee0eede0" />

but the indexing for Argo says a step is still waiting

<img width="427" alt="Image" src="https://github.com/user-attachments/assets/05d70108-11d4-4ea2-8060-029046b661b5" />

**Comment by justinlittman** [comment]
The logs confirm the concurrency hypothesis:
```
[2025-03-10T15:26:33-07:00] [INFO] [Indexing] Reindexing druid:bb518sf0530 from app/jobs/reindex_by_druid_job.rb:16:in 'ReindexByDruidJob#work' with trace_id=65a151ed-d13e-4282-91b8-1bccf0ca0565
[2025-03-10T15:26:34-07:00] [INFO] [Indexing] Reindexing druid:bb518sf0530 from app/jobs/reindex_by_druid_job.rb:16:in 'ReindexByDruidJob#work' with trace_id=8479c328-d1a4-48d1-8087-c5ba37a273ed
[2025-03-10T15:26:34-07:00] [INFO] [Indexing] Committing druid:bb518sf0530 with trace_id=d7c940f2-133f-4d6e-b97c-b2de5ba2d706
[2025-03-10T15:26:34-07:00] [INFO] [Indexing] Committing druid:bb518sf0530 with trace_id=8479c328-d1a4-48d1-8087-c5ba37a273ed
[2025-03-10T15:26:34-07:00] [INFO] [Indexing] Reindexing druid:bb518sf0530 from app/jobs/reindex_by_druid_job.rb:16:in 'ReindexByDruidJob#work' with trace_id=8921e3ef-c231-4a5b-99e4-89fdbd3137b9
[2025-03-10T15:26:34-07:00] [INFO] [Indexing] Committing druid:bb518sf0530 with trace_id=8921e3ef-c231-4a5b-99e4-89fdbd3137b9
[2025-03-10T15:26:35-07:00] [INFO] [Indexing] Committing druid:bb518sf0530 with trace_id=65a151ed-d13e-4282-91b8-1bccf0ca0565
```

You can see that the first reindexing is the last committed.

**Comment by justinlittman** [comment]
Perhaps we can use https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/concerns/unique_job.rb?

**Comment by justinlittman** [comment]
As specified above, the problem is that there are multiple reindexing jobs occurring concurrently for the same item. For whatever reason, sometimes those jobs didn't complete in the expected order, causing solr records with older data to overwrite solr records with newer data.

#5279 addresses this problem by forcing only a single reindexing job to be processed at a time for the same item using a redis lock. A job will retry a certain number of times when until it can acquire a lock. In theory, this should address the problem because the jobs writing solr records with older data complete before the jobs that write solr records with newer data are started.

This might have unintended consequences. Hypothetically, these might include:
* A large backlog of retrying reindexing jobs impacting other jobs. To attempt to reduce this risk, retries are put on the low priority queue.
* A noticeable latency in reindexing due to above and because there is a 3 second delay between each retry.

Or, it might just work.
